import BasicHypergeometricIntegralsFunctionsDefinedCanonicalLaneLean.AdmissibleClass
import BasicHypergeometricIntegralsFunctionsDefinedCanonicalLaneLean.BasicHypergeometricSeries
import BasicHypergeometricIntegralsFunctionsDefinedCanonicalLaneLean.IntegralRepresentations
import BasicHypergeometricIntegralsFunctionsDefinedCanonicalLaneLean.TransformationFormulas
import BasicHypergeometricIntegralsFunctionsDefinedCanonicalLaneLean.BridgeLemmas
import BasicHypergeometricIntegralsFunctionsDefinedCanonicalLaneLean.GateLemmas
import BasicHypergeometricIntegralsFunctionsDefinedCanonicalLaneLean.FinalTheorem